default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clone_book_development

test:
  <<: *default
  database: clone_book_test

production:
  <<: *default
  database: clone_book_production
  username: clone_book
  password: <%= ENV['CLONE_BOOK_DATABASE_PASSWORD'] %>
